### ISSUE TITLE
Avoid platform-specific attributes 

### ISSUE THREAD

**Issue by dkim286** [nle244/4GP-Password-Manager#1]
# Problem 

Program crashes on startup on some platforms: 

```console
$ python pm.py 
Traceback (most recent call last):
  File "/home/person/courses/491/4GP-Password-Manager/pm.py", line 6, in <module>
    pm.core.main()
  File "/home/person/courses/491/4GP-Password-Manager/pm/core.py", line 4, in main
    root = MainWindow() 
  File "/home/person/courses/491/4GP-Password-Manager/pm/ui.py", line 18, in __init__
    self.attributes('-toolwindow', True)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-toolwindow": must be -alpha, -topmost, -zoomed, -fullscreen, or -type
```
# Cause 

According to the docs, `toolwindow` is a Windows-specific attribute: 
- https://wiki.tcl-lang.org/page/wm+attributes
- https://tcl.tk/man/tcl8.6/TkCmd/wm.htm#M6

# Fix 

If we're going to use platform-specific attribs, it should be checked first:

```py
import platform

if platform.system() == 'Windows': 
    self.attributes('-toolwindow', True)
```

If not, we should stick to platform-independent attribs (source: https://tcl.tk/man/tcl8.6/TkCmd/wm.htm#M6):

>All platforms support the following attributes (though X11 users should see the notes below):
>- `-alpha`
>    - Specifies the alpha transparency level of the toplevel. It accepts a value from 0.0 (fully transparent) to 1.0 (opaque). Values outside that range will be constrained. Where not supported, the -alpha value remains at 1.0.
>- `-fullscreen`
>    - Places the window in a mode that takes up the entire screen, has no borders, and covers the general use area (i.e. Start menu and taskbar on Windows, dock and menubar on OSX, general window decorations on X11).
>- `-topmost`
>    - Specifies whether this is a topmost window (displays above all other windows).

**Comment by dkim286** [comment]
Potential fix: [5ce068](https://github.com/nle244/4GP-Password-Manager/commit/5ce0686b3c6a7102800bda753546b6c32cf45630)
